 /******************************************************************************
 *
 * Module: Ultrasonic sensor
 *
 * File Name:  ultrasonic_sensor.c
 *
 * Description: Source file for the AVR Ultrasonic driver
 *
 * Author: Narden Sobhy Shaker
 *
 *******************************************************************************/

#include "ultrasonic_sensor.h"
#include "gpio.h"
#include "icu.h"
#include <util/delay.h>

static uint8 g_edgeCount = 0;
static uint16 g_timeHigh = 0;


static void Ultrasonic_edgeProcessing(void);

/*
 * Description : Function to initialize the Ultrasonic driver
 * 	1. Initialize the ICU driver.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the Trigger pin direction by use the GPIO driver.
 */
void Ultrasonic_init(void){

	/* Create configuration structure for ICU driver */
	Icu_ConfigType ICU_Config={F_CPU_8,RISING};
	/* Initialize the ICU driver.*/
	Icu_init(& ICU_Config);
	/* Setup the ICU call back function.*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	/*  Setup the Trigger pin direction by use the GPIO driver.*/
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID ,PIN_OUTPUT);


}

/*
 * Description : Function to Send the Trigger pulse to the ultrasonic.
 */
static void Ultrasonic_Trigger(void){

	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_HIGH);
	/* delay for processing = 10ns */
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_LOW);

}

/*
 * Description : Function used to:
 * 	1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 	2. Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void){

	uint16_t distance;

	Icu_clearTimerValue();
	Ultrasonic_Trigger();
	while(g_edgeCount != 2);
	g_edgeCount=0;
	distance = g_timeHigh/58.8;
	return  distance;

}

/*
 * Description :
 * 	1. This is the call back function called by the ICU driver.
 * 	2. This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
static void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
	}

}
